### ISSUE TITLE
i18n: automatically extract the translations using a script

### ISSUE THREAD

**Issue by lavocatt** [artemiscloud/activemq-artemis-self-provisioning-plugin#206]
See https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/discussions/181

**TODO list:**
- [ ] Use https://www.i18next.com/how-to/extracting-translations to extract the translations.
- [ ] Create a yarn command to start the script
- [ ] Make sure the CI fail if there are strings that are not extracted properly

**Comment by Msarawan** [comment]
Closed as completed via: [PR#290](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/pull/290)
